### ISSUE TITLE
Add directions on modifying the code server password in the docker-compose.yml file

### ISSUE THREAD

**Issue by aott33** [joyja/tentacle-plc#26]
For example, show how the user can add an environment var to the docker-compose.yml file

```
code-server:
    user: 0:0
    restart: always
    container_name: tentacle-plc-code-server
    image: codercom/code-server:4.0.2
    ports:
      - 8080:8080
    networks:
      - upstream
    volumes:
      - tentacle-plc-runtime:/home/coder/project:rw
    environment:
      - DOCKER_USER=root
      - PASSWORD=Password
```
